version: '3.8'

services:
  TPO13_postgres:
    image: postgres:16-alpine
    container_name: TPO13_postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - TPO13_postgres:/var/lib/postgresql/data

  # cac_mysql:
  #   image: mysql:5.7
  #   container_name: cac_mysql
  #   ports:
  #     - 13306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: database
  #   # volumes:
  #   #   - cac_mysql:/var/lib/mysql

  TPO13_pgadmin:
    image: dpage/pgadmin4
    container_name: TPO13_pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: Chefs123@admin.com
      PGADMIN_DEFAULT_PASSWORD: Chefs123
    volumes:
      - TPOO13_pgadmin:/var/lib/pgadmin
    depends_on:
      - TPO13_postgres



  # cac_adminer:
  #   image: adminer
  #   container_name: cac_adminer
  #   ports:
  #     - 18080:8080
  #   depends_on:
  #     - cac_mysql

  tpo13_backend:
    image: tpo13_backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpo13_backend
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
      
networks:
  default:
    name: tpo13_sql

volumes:
  TPO13_postgres:
  TPOO13_pgadmin: